# Generated by Django 4.2.5 on 2023-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='football_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_regno', models.IntegerField()),
                ('p_name', models.CharField(max_length=20)),
                ('p_age', models.IntegerField()),
                ('p_country', models.CharField(max_length=20)),
                ('p_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
